spring:
  application:
    name: eureka-ha

---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      # defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
      defaultZone: http://peer2:8762/eureka/
    # register-with-eureka: false

---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      # defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
      defaultZone: http://peer1:8761/eureka/

---
server:
  port: 8763
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

# 构建docker镜像
# docker build -t springcloud/eureka .

# 运行docker镜像
# docker run -p 8761:8761 -d springcloud/eureka
# docker run -p 8762:8761 -d springcloud/eureka